ERROR/2023-05-29 14:26:00/Falló: select from bsc_idioma; #1064 - Algo está equivocado en su sintax cerca 'from bsc_idioma' en la linea 1
ERROR/2023-05-29 17:41:01/Falló: insert into bsc_idioma(id, idioma) values ('9','prueba'); #1062 - Entrada duplicada '9' para la clave 'PRIMARY'
ERROR/2023-05-29 17:56:01/Falló: insert into bsc_idioma(id, idioma) values ('9','prueba'); #1062 - Entrada duplicada '9' para la clave 'PRIMARY'
ERROR/2023-05-29 17:57:33/Falló: insert into bsc_idioma(id, idioma) values ('9','prueba'); #1062 - Entrada duplicada '9' para la clave 'PRIMARY'
ERROR/2023-05-30 08:45:47/Archivo: C:\Users\casuarez\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\errorhandler.py, línea: 245, función: check_response, código: raise exception_class(message, screen, stacktrace)
ERROR/2023-05-30 08:51:51/Archivo: C:\Users\casuarez\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\errorhandler.py, línea: 244, función: check_response, código: raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here
ERROR/2023-05-30 08:54:53/Archivo: C:\Users\casuarez\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\errorhandler.py, línea: 245, función: check_response, código: raise exception_class(message, screen, stacktrace)
ERROR/2023-05-30 09:00:58/Archivo: C:\Users\casuarez\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\errorhandler.py, línea: 245, función: check_response, código: raise exception_class(message, screen, stacktrace)
ERROR/2023-05-30 09:17:20/Archivo: C:\Users\casuarez\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\errorhandler.py, línea: 245, función: check_response, código: raise exception_class(message, screen, stacktrace)
ERROR/2023-05-30 10:38:37/Archivo: C:\Users\casuarez\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\errorhandler.py, línea: 244, función: check_response, código: raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here
ERROR/2023-05-30 15:31:12/Archivo: C:\Users\casuarez\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\errorhandler.py, línea: 244, función: check_response, código: raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here
ERROR/2023-05-30 15:44:52/Archivo: C:\Users\casuarez\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\errorhandler.py, línea: 244, función: check_response, código: raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here
ERROR/2023-05-30 16:21:27/Archivo: log.py, línea: 12, función: escribir_bitacora, código: 
ERROR/2023-05-30 16:24:08/Archivo: log.py, línea: 12, función: escribir_bitacora, código: 
